import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SidebarProvider } from "./context/sidebar-context";
import { NewClassroomModalProvider } from "./context/new-classroom-modal-context";
import { Toaster } from "@/app/components/ui/sonner";
import SessionProvider from "./components/session-provider";
import { TooltipProvider } from "./components/ui/tooltip";

const inter = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "GPT de Professor",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <head>
        {/* eslint-disable-next-line @next/next/no-sync-scripts */}
        <script
          crossOrigin="anonymous"
          src="//unpkg.com/react-scan/dist/auto.global.js"
        />
        {/* rest of your scripts go under */}
      </head>
      <body className={`${inter.variable} antialiased overflow-y-hidden`}>
        <SessionProvider>
          <SidebarProvider>
            <NewClassroomModalProvider>
              <TooltipProvider>
                {children}
                <Toaster
                  position="top-center"
                  className="whitespace-pre-wrap"
                />
              </TooltipProvider>
            </NewClassroomModalProvider>
          </SidebarProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
