import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "./context/SidebarContext";
import { NewClassroomModalProvider } from "./context/NewClassroomModalContext";
import { Toaster } from "@/app/components/ui/sonner";

const montserrat = Montserrat({
    weight: ['400', '500', '600', '700'],
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-montserrat',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <NewClassroomModalProvider>
        <html>
          <body className={`${montserrat.variable} antialiased`}>
            {children}
            <Toaster position="top-center" />
          </body>
        </html>
      </NewClassroomModalProvider>
    </SidebarProvider>
  );
}
